name: Scrape and Update Data

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for GITHUB_TOKEN to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install puppeteer@latest

      - name: Run scraper
        run: node server.js

      - name: Commit and push data
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Stage all modified files (or swap for `git add data.json` if you only want that one)
          git add -A
          git diff --cached --quiet || git commit -m "⏰ Hourly data update"
          
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/hdeavers1/NEOH_Leaderboard
          git push origin HEAD


          
          
